### ISSUE TITLE
store images outside of the repository.

### ISSUE THREAD

**Issue by art0007i** [RileyGuy/Resonance#1]
currently you have a 22 MB gif in the repo. this means that if I want to edit the code of your mod, I have to download the 22 MB gif.

for files under 10MB you can just drag and drop them into the readme editor on the github website, and it will automatically insert it into the readme.
for anything above that you'd have to store it externally unfortunately, but I guess creating a gh repo where you upload all of your images could work

**Comment by BlueCyro** [comment]
The reason they're in the repository is because I use vscode's offline markdown editor. I don't plan on adding any more images, and if I end up needing to I'll likely figure something else out. As it stands the amount of data is quite small and I don't feel it's problematic given how few images there are. Plus, this means that the git repo can be used offline or cloned to other git providers should the need arise. Even self-hosted repos would work.

**Comment by art0007i** [comment]
Fair enough. You make some good points about keeping the media in repo.
Though I cannot agree that the amount of data is small. The media in this repo is over 400x larger than everything else combined. It took like half a minute for me to clone the repo, that's long enough to make me think that my git broke.
